### ISSUE TITLE
[Remediation] Mass replace URIs by field

### ISSUE THREAD

**Issue by sseymore** [OregonDigital/oregondigital#1550]
Mass replace URIs by field. 

- Metadata folks check each URI in [UO_label_remediation](https://docs.google.com/spreadsheets/d/1tH0v99OKTxwB7PNS6_nbBlH2Tl2LvImqf3Nd4a8t348/edit#gid=264366692) sheet. 
- Once done, if there are any mass replace remediation actions needed, create a spreadsheet with old URIs in first column and the replacement URI in the second column. 
- Put that sheet [here](https://drive.google.com/drive/u/0/folders/1GVUHSGrn2WWN5lnOQjIKrVVuaBzKtdSM) for Linda.
- Check box next to field under Ready for Linda and notify her in a comment. 
- See local_collection_name for example.

Ready for Linda:
- [ ] local collection name
- [ ] repository
- [ ] publisher
- [ ] tgn
- [ ] ethnographic term
- [ ] military branch
- [ ] worktype
- [ ] style period
- [ ] subject
- [ ] recipient
- [ ] collector (no PIDs for this one? question for @lsat12357)
- [ ] photographer
- [ ] lyricist
- [ ] interviewee
- [ ] donor
- [ ] composer
- [ ] author
- [ ] contributor
- [ ] creator

Remediated by Linda:
- [ ] local collection name
- [ ] repository
- [ ] publisher
- [ ] tgn
- [ ] ethnographic term
- [ ] military branch
- [ ] worktype
- [ ] style period
- [ ] subject
- [ ] recipient
- [ ] collector (no PIDs for this one? question for @lsat12357)
- [ ] photographer
- [ ] lyricist
- [ ] interviewee
- [ ] donor
- [ ] composer
- [ ] author
- [ ] contributor
- [ ] creator

**Comment by sseymore** [comment]
@lsat12357 local collection name is ready for remediation. thanks!

**Comment by lharka** [comment]
@lsat12357 tgn, ethnographic term,  and worktype are ready for remediation. In the spreadsheet, rows flagged in orange represent items needing mass replacement with script (i.e., >20 items with the same URI replacement). Thank you!

**Comment by jsimic** [comment]
@lsat12357 Ready for mass replace: photographer, donor, author, contributor, creator. There is nothing for lyricist, interviewee or composer, so I am removing those from the checklists

**Comment by lsat12357** [comment]
Can you please check to make sure that you are using the correct form of the terms? eg, the authors list is using https rather than http for opaquenamespace

**Comment by jsimic** [comment]
@lsat12357 Done

**Comment by sseymore** [comment]
@lsat12357 repository is ready for mass replace URIs. Thank you.

**Comment by sseymore** [comment]
Edited to remove tgn, ethno term, military branch, recipient, and collector since all corrected by hand. Trying to finish publisher ASAP.

**Comment by sseymore** [comment]
There is actually no mass replacements needed for publisher, so also marked that complete.

**Comment by lsat12357** [comment]
re replaceURIs_repository.xlsx
I noticed that towards the end, there are a few replacement uris that have special chars in them, for instance http://opaquenamespace.org/ns/repository/MuséedArtContemporainMontreal
so I tried replacing the é with a regular e, but it still does not resolve. how do you want to proceed? If you want me to run them anyway, I can.

**Comment by sseymore** [comment]
I thought I got them all. I checked again and corrected these:

http://opaquenamespace.org/ns/repository/ChâteauMuséeBoulogna
http://opaquenamespace.org/ns/repository/MuséeLapidaireVienne
http://opaquenamespace.org/ns/repository/MuséedArtContemporainMontreal

I added these to the URIs that need to be created in opns. Sorry about that.
