### ISSUE TITLE
Audio player in record view not working

### ISSUE THREAD

**Issue by kestlund** [OregonDigital/oregondigital#724]
Urgent problem, as class is using these. The download works. 

Example: http://oregondigital.org/sets/uo-veterans/oregondigital:br86b4223
![screen shot 2015-01-08 at 11 33 30 am](https://cloud.githubusercontent.com/assets/2481327/5669159/4115ef94-972a-11e4-98cf-3b3f352bb725.png)

**Comment by terrellt** [comment]
@kestlund Is the problem the download -does- work or doesn't work? Because I get an error page

**Comment by terrellt** [comment]
@decimalator Did you have time to get ffmpeg installed on hydra-worker1?

**Comment by mickeroo** [comment]
From the Hydra meeting on 1/23/15:
- Have Duncan talk to @decimalator to see if he can take care of it while @decimalator is working on putting out SILS fires
- **Would need to re-run derivatives once this is in place**

**Comment by terrellt** [comment]
http://oregondigital.library.oregonstate.edu/catalog/oregondigital:w9505112w

Done. Re-queuing audio derivatives.

**Comment by sseymore** [comment]
Did these derivatives ever get re-made or are they buried in the queue? No audio in UO Vets is working. 

http://oregondigital.org/sets/uo-veterans?f%5Bdesc_metadata__format_label_sim%5D%5B%5D=audio%2Fmpeg%24http%3A%2F%2Fpurl.org%2FNET%2Fmediatypes%2Faudio%2Fmpeg&q=&search_field=all_fields

**Comment by wickr** [comment]
They shouldn't be buried in the queue at this point, it should only go back a couple weeks.

This one works: http://oregondigital.library.oregonstate.edu/catalog/oregondigital:w9505112w

But I just queued up one of the ones that didn't work. http://oregondigital.org/sets/uo-veterans/oregondigital:5999n405f

It finished but it's still not working.

**Comment by wickr** [comment]
@terrellt The only thing I notice is, when I go to Edit the one that doesn't work, for the file it shows the filename as whatever.mp3  but for the one that does work it shows the usual "File Datastream". Are the mp3s possibly not correctly associated with the datastream?

**Comment by terrellt** [comment]
I don't think any derivatives will work right now, I had to shut off ffmpeg because it was freezing on some videos and holding up the derivative queue.

**Comment by terrellt** [comment]
Er, any audio/video derivatives.

**Comment by srabun** [comment]
Audio player still broken: https://github.com/OregonDigital/oregondigital/issues/724 in UO Vets: http://oregondigital.library.oregonstate.edu/sets/uo-veterans/oregondigital:5999n405f 
audio player works, but Trey had turned off derivatives for a while. Running derivatives right now.
Ryan knows how to do this. Trey will document - Linda run derivatives on UO Vets

**Comment by jsimic** [comment]
Is there any fix for the time-slider not working on video? See http://oregondigital.library.oregonstate.edu/sets/corazon-de-dixie/oregondigital:fx71bc60m and http://oregondigital.library.oregonstate.edu/sets/corazon-de-dixie/oregondigital:df70hn10s

**Comment by wickr** [comment]
@jsimic It's apparently either a server issue, since in the HTML5 players seeking/scrubbing is a new web request, but I looked and our server seems to be responding to the HTTP 206 partial content requests. Or it might mean we need to do a Javascript tweak to the player, or (hopefully not) change the encoding of the webm video file. http://stackoverflow.com/questions/8088364/html5-video-will-not-loop
